/// Flutter icons Finance
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/

import 'package:flutter/widgets.dart';

class Finance {
  Finance._();

  static const _kFontFam = 'Finance';
  static const _kFontPkg = null;

  static const IconData list =
      IconData(0xf03a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper =
      IconData(0xf1ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glasses =
      IconData(0xf530, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_wave =
      IconData(0xf53a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
